version: '3'

services:
  frontend:
    build: .
    ports:
      - "8081:8080"
    networks:
      - todoapp

  db:
    image: postgres:latest
    volumes:
    - "db:/var/lib/postgresql/data"
    - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - todoapp

networks:
  todoapp:
    driver: bridge

volumes:
  db:
